### ISSUE TITLE
The problem with PyMesh

### ISSUE THREAD

**Issue by liyue9129** [CAODH/SurfDock#6]
Hi！
Great work！
I have encountered several issues during the [computeTargetMesh_test_samples.py.]，This calls fixmesh.py -> which leads to the problem，[here](https://github.com/CAODH/SurfDock/blob/master/comp_surface/prepare_target/fixmesh.py#L50)，
The associated stderr output is as follows：
![image](https://github.com/user-attachments/assets/c837db81-485a-4655-a85c-8ac181264fb7)

So, what should I do address this issue？
Thank you！
Best wishes !

**Comment by CAODH** [comment]
> Hi！ Great work！ I have encountered several issues during the [computeTargetMesh_test_samples.py.]，This calls fixmesh.py -> which leads to the problem，[here](https://github.com/CAODH/SurfDock/blob/master/comp_surface/prepare_target/fixmesh.py#L50)， The associated stderr output is as follows： ![image](https://private-user-images.githubusercontent.com/109455868/393468984-c837db81-485a-4655-a85c-8ac181264fb7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3MDg0MTYsIm5iZiI6MTczMzcwODExNiwicGF0aCI6Ii8xMDk0NTU4NjgvMzkzNDY4OTg0LWM4MzdkYjgxLTQ4NWEtNDY1NS1hODVjLThhYzE4MTI2NGZiNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwOVQwMTM1MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMzQ1MTJjMzU3ODIwYjlkN2U2NzZjZjBkN2ExOWQ2NWM4YjI1NTY5ZmJhYmU4N2I2ZWNmZmFhZGY2YmQyMjc4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.q213RRepOfq5tRACPr5xGghvHUMYqB2TtEyUXkkYKNM)
> 
> So, what should I do address this issue？ Thank you！ Best wishes !

![image](https://github.com/user-attachments/assets/2a1fd602-1f55-4c3c-83d7-7b180f88afcc)
please follow this commands to install pymesh and only import pymesh.
