### ISSUE TITLE
python: can't open file '/home/lizheng/SurfDock-Version_0.0.1/esm/scripts/extract.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by lizhengcaas** [CAODH/SurfDock#7]
"Dear Author, 

I would like to ask whether the 'esm' folder is generated by a script or created in some other way. When I run the `eval_samples.sh` script, I keep encountering this error. I also noticed that the test data I downloaded does not include this folder."

**Comment by AndChenCM** [comment]
Hi lizheng,

The esm folder is from https://github.com/facebookresearch/esm. You should install their repository and execute the command.

**Comment by CAODH** [comment]
> "Dear Author,
> 
> I would like to ask whether the 'esm' folder is generated by a script or created in some other way. When I run the `eval_samples.sh` script, I keep encountering this error. I also noticed that the test data I downloaded does not include this folder."


> "Dear Author,
> 
> I would like to ask whether the 'esm' folder is generated by a script or created in some other way. When I run the `eval_samples.sh` script, I keep encountering this error. I also noticed that the test data I downloaded does not include this folder."

hi lizheng please check the updated README 
![image](https://github.com/user-attachments/assets/6651a178-29dc-4481-990a-ba4fa5139139)

**Comment by lizhengcaas** [comment]
> > "Dear Author,
> > I would like to ask whether the 'esm' folder is generated by a script or created in some other way. When I run the `eval_samples.sh` script, I keep encountering this error. I also noticed that the test data I downloaded does not include this folder."
> 
> > "Dear Author,
> > I would like to ask whether the 'esm' folder is generated by a script or created in some other way. When I run the `eval_samples.sh` script, I keep encountering this error. I also noticed that the test data I downloaded does not include this folder."
> 
> hi lizheng please check the updated README ![image](https://private-user-images.githubusercontent.com/53987775/394585197-6651a178-29dc-4481-990a-ba4fa5139139.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MDU3MzMsIm5iZiI6MTczNDQwNTQzMywicGF0aCI6Ii81Mzk4Nzc3NS8zOTQ1ODUxOTctNjY1MWExNzgtMjlkYy00NDgxLTk5MGEtYmE0ZmE1MTM5MTM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDAzMTcxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjODNlNGI1NDI5OTZiZjYzZDQ1OTU5OTI2ODk2NDJiNzA5ZmI2Yjk5YTNkYjhhMjAzZmExZjg0ZDQ5YzZhMGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HCBwvd14opw8Iuo4R91Vh63ePlUgwkD511FcGa3wpIo)


This is my issue, thank you for your help in clarifying it.

**Comment by lizhengcaas** [comment]
> > "Dear Author,
> > I would like to ask whether the 'esm' folder is generated by a script or created in some other way. When I run the `eval_samples.sh` script, I keep encountering this error. I also noticed that the test data I downloaded does not include this folder."
> 
> > "Dear Author,
> > I would like to ask whether the 'esm' folder is generated by a script or created in some other way. When I run the `eval_samples.sh` script, I keep encountering this error. I also noticed that the test data I downloaded does not include this folder."
> 
> hi lizheng please check the updated README ![image](https://private-user-images.githubusercontent.com/53987775/394585197-6651a178-29dc-4481-990a-ba4fa5139139.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MDU3MzMsIm5iZiI6MTczNDQwNTQzMywicGF0aCI6Ii81Mzk4Nzc3NS8zOTQ1ODUxOTctNjY1MWExNzgtMjlkYy00NDgxLTk5MGEtYmE0ZmE1MTM5MTM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDAzMTcxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjODNlNGI1NDI5OTZiZjYzZDQ1OTU5OTI2ODk2NDJiNzA5ZmI2Yjk5YTNkYjhhMjAzZmExZjg0ZDQ5YzZhMGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HCBwvd14opw8Iuo4R91Vh63ePlUgwkD511FcGa3wpIo)

This is my issue, thank you for your help in clarifying it.

**Comment by lizhengcaas** [comment]
> Hi lizheng,
> 
> The esm folder is from https://github.com/facebookresearch/esm. You should install their repository and execute the command.



This is my issue, thank you for your help in clarifying it.
