### ISSUE TITLE
how to get the environment of precomputed_arrays in "so3.py"?

### ISSUE THREAD

**Issue by kelly1210** [CAODH/SurfDock#9]
when I run the file of "eval_samples.sh", there is an error that "FileNotFoundError: [Errno 2] No such file or directory:***/precomputed/precomputed_arrays/.so3_omegas_array2.npy". But I dont know how to get the npy files? I am looking forward to your guidance. Thank you so much!

**Comment by kelly1210** [comment]
Thank you, the issue has been resolved.

**Comment by shekfeh** [comment]
Hi how did you resolve this?

**Comment by CAODH** [comment]
> Thank you, the issue has been resolved.

thanks! :)
